// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWxXExBLiM4-cJwefdrxVk3Xflk77xlg',
    appId: '1:558257555900:web:75d3e1fa02c620addec3b9',
    messagingSenderId: '558257555900',
    projectId: 'booq-e2f02',
    authDomain: 'booq-e2f02.firebaseapp.com',
    storageBucket: 'booq-e2f02.firebasestorage.app',
    measurementId: 'G-3SPTL4V4W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fzNlcUapMZZ-Z6XdjxbO7bF1cZjuX3M',
    appId: '1:558257555900:android:dff48d9d42e9fabbdec3b9',
    messagingSenderId: '558257555900',
    projectId: 'booq-e2f02',
    storageBucket: 'booq-e2f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2OXTDPG1wQdHiA8mwTdNcC-A6mjzW38',
    appId: '1:558257555900:ios:e21ef3b3e44579d1dec3b9',
    messagingSenderId: '558257555900',
    projectId: 'booq-e2f02',
    storageBucket: 'booq-e2f02.firebasestorage.app',
    iosBundleId: 'com.example.booqLastAttempt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2OXTDPG1wQdHiA8mwTdNcC-A6mjzW38',
    appId: '1:558257555900:ios:e21ef3b3e44579d1dec3b9',
    messagingSenderId: '558257555900',
    projectId: 'booq-e2f02',
    storageBucket: 'booq-e2f02.firebasestorage.app',
    iosBundleId: 'com.example.booqLastAttempt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvWxXExBLiM4-cJwefdrxVk3Xflk77xlg',
    appId: '1:558257555900:web:0bab9f7ec03a460fdec3b9',
    messagingSenderId: '558257555900',
    projectId: 'booq-e2f02',
    authDomain: 'booq-e2f02.firebaseapp.com',
    storageBucket: 'booq-e2f02.firebasestorage.app',
    measurementId: 'G-KDYS8WKW33',
  );

}